# docker build . -t compile-jar:v1
# docker -d -v ambulance_app:/Ambulance-Data-Parsing/target --name Compile_JAR compile-jar:v1

FROM openjdk:17-alpine
RUN mkdir Ambulance-Data-Parsing
ADD Ambulance-Data-Parsing /Ambulance-Data-Parsing
WORKDIR /Ambulance-Data-Parsing
ENTRYPOINT ["/bin/sh","/Ambulance-Data-Parsing/mvnw","package"]
