version: "0.1"
services:
  postgres-db:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - /home/user/Ambulance-Data-Parsing/postgres-db:/var/lib/postgresql/data

  ambulance-app:
    build: /home/user/Ambulance-Data-Parsing/devops/ambulance-server
    ports:
      - "8080:8080"
    volumes:
      - /home/user/Ambulance-Data-Parsing/target:/target
      - /home/user/Ambulance-Data-Parsing/src/data:/src/data
    depends_on:
      - postgres-db
